- docs/src/components/Nav.tsx
- docs/src/components/examples/Scatter.tsx
- docs/src/index.tsx
- src/components/ScatterLayer.tsx
- src/components/SizedPlot.tsx
- src/stats/index.ts
- src/stats/scatter.ts
- src/types/index.ts
- src/utils/getSymbolScale.ts
> Add scatter plot type with symbol scale

- src/utils/useHoverLineIndices.ts
Before:
After:
Previously, the line crosshair would only snap to the nearest point if it was within 20 pixels.  This commit changes that behavior, so that the line crosshair will snap to the nearest point, no matter how near it is.
This provides a nicer user experience. It also lets us fine tune the spatial index used to look up hover points. In particular, since the `INDEX_BIN_WIDTH` constant is no longer coupled to the user experience of how much the crosshair will snap, we can change it at will. This commit shrinks that constant, which should speed up reads from the index.
> Always snap line crosshair to nearest point

- package-lock.json
- package.json
- src/index.ts
- src/stats/bin.test.ts
- src/types/index.ts
- src/utils/fluxToTable.test.ts
- src/utils/fluxToTable.ts
> Add Flux CSV to Table adapter

- package.json
- src/components/HeatmapHoverLayer.tsx
- src/components/HeatmapLayer.tsx
- src/components/LineLayer.tsx
- src/components/SizedPlot.tsx
- src/utils/drawHeatmap.ts
- src/utils/getHistogramTooltipData.ts
- src/utils/heatmapTooltip.ts
- src/utils/tooltip.ts
> Show tooltips for heatmap layers

- src/types/index.ts
> Revert "Convert numeric type to number array"

- src/components/Axes.tsx
- src/components/HeatmapHoverLayer.tsx
- src/components/HeatmapLayer.tsx
- src/components/HistogramLayer.tsx
- src/components/LineHoverLayer.tsx
- src/components/LineLayer.tsx
- src/components/ScatterLayer.tsx
- src/components/Tooltip.tsx
Added data-testid to a few elements for cypress tests
> Bonitoo cypress

- CONTRIBUTING.md
- package-lock.json
- package.json
- src/components/Axes.tsx
- src/components/Brush.tsx
- src/components/HeatmapHoverLayer.tsx
- src/components/HeatmapLayer.tsx
- src/components/HistogramLayer.tsx
- src/components/LineHoverLayer.tsx
- src/components/LineLayer.tsx
- src/components/Plot.tsx
- src/components/ScatterLayer.tsx
- src/components/SizedPlot.tsx
- src/components/Tooltip.tsx
- src/utils/useTooltipElement.ts
- stories/snapshotTests.stories.tsx
Thank you, thank you, I'd like to collect my graphic design awards now.
> Rename library to "giraffe"

- src/components/LineHoverLayer.tsx
- src/components/LineLayer.tsx
- src/constants/index.ts
- src/types/index.ts
- src/utils/drawLines.ts
- stories/index.stories.tsx
- stories/snapshotTests.stories.tsx
> Support shading area below lines

- src/transforms/heatmap.test.ts
- src/transforms/heatmap.ts
- src/transforms/histogram.test.ts
- src/transforms/histogram.ts
- src/utils/resolveDomain.ts
Connect https://github.com/influxdata/influxdb/issues/14153
> Fix heatmap crash when using domain of zero-width

- src/utils/fromFlux.test.ts
- src/utils/fromFlux.ts
Connect https://github.com/influxdata/influxdb/issues/15017
> Handle parsing Flux CSV responses with newlines

- giraffe/src/utils/useHoverPointIndices.ts
We need to compare y position to width of elt not height :(
> Fix bug determining y position hover bounds

- stories/.storybook/webpack.config.js
- stories/package.json
- stories/src/customLayer.stories.tsx
- stories/src/data.ts
- stories/src/helpers.tsx
- stories/src/index.stories.tsx
- stories/src/sin.stories.tsx
- stories/src/sin.ts
- stories/src/snapshotTests.stories.tsx
- yarn.lock
Closes https://github.com/influxdata/giraffe/issues/117
> feat: Add hot reloading to stories

- giraffe/src/types/index.ts
Removes unnecessary interface extension.
> refactor: remove unnecessary interface extension

- giraffe/src/utils/formatters.test.ts
- giraffe/src/utils/formatters.ts
Closes #125 
Updated the timeFormatter utility function and updated the tests to reflect the changes made to the timeFormatter
> fix: broken tests and formatting

- giraffe/src/utils/formatters.test.ts
- giraffe/src/utils/formatters.ts
- stories/src/index.stories.tsx
Closes https://github.com/influxdata/influxdb/issues/16122
> fix: use dependency's 12-hour format when specified

- giraffe/README.md
- giraffe/package.json
- Adds keywords for npm registry search
- Edits minor mistakes in docs
> chore: add keywords for npm search and edit docs

- giraffe/README.md
- giraffe/src/components/Gauge.tsx
- giraffe/src/components/GaugeLayer.tsx
- giraffe/src/components/SizedPlot.tsx
- giraffe/src/constants/gaugeStyles.ts
- giraffe/src/index.ts
- giraffe/src/types/index.ts
- giraffe/src/utils/PlotEnv.ts
- giraffe/src/utils/formatStatValue.test.ts
- giraffe/src/utils/formatStatValue.ts
- giraffe/src/utils/get.test.ts
- giraffe/src/utils/get.ts
- giraffe/src/utils/isNumber.test.ts
- giraffe/src/utils/isString.test.ts
- giraffe/src/utils/isSymbol.test.ts
- giraffe/src/utils/isSymbol.ts
- giraffe/src/utils/range.ts
- stories/src/data/gaugeLayer.ts
- stories/src/gauge.stories.tsx
Closes #168 
Add the Gauge visualization
> feat: add Gauge visualization

- giraffe/src/utils/formatStatValue.test.ts
- giraffe/src/utils/formatStatValue.ts
> fix: leave strings as strings in formatStatValue

- giraffe/package.json
- giraffe/src/utils/getMargins.ts
- giraffe/src/utils/identityMerge.test.ts
- stories/package.json
- yarn.lock
Keep pace with influxdb for consistent styling
> chore: update prettier

- giraffe/src/utils/simplify.ts
Closes https://github.com/influxdata/giraffe/issues/216
Closes influxdata/EAR#1647
Changing from recursive calls of `simplifyDouglasPeuckerHelper` to a while loop seems to have done the trick.
> fix(line): call stack exceeded

- giraffe/package.json
- stories/package.json
- yarn.lock
> chore: upgrade Typescript

- giraffe/jest.config.js
- giraffe/src/types/index.ts
- giraffe/src/utils/fluxParsing.ts
- giraffe/src/utils/fromFlux.test.ts
- giraffe/src/utils/fromFlux.ts
Added a very generic input output test for fromFlux stability to ensure that everything works as it should
> Added a fromFlux test for stability

- .eslintrc.json
- giraffe/src/utils/isEqual.ts
In an effort to bring consistent style and clarity, we will enforce curly braces: https://eslint.org/docs/rules/curly
> chore: enforce curly braces

- giraffe/src/components/Gauge.tsx
- giraffe/src/utils/formatStatValue.ts
> fix: gauge needle bug

- giraffe/README.md
- giraffe/src/components/Plot.tsx
- giraffe/src/components/SizedPlot.tsx
- giraffe/src/components/SizedTable.tsx
- stories/src/gauge.stories.tsx
- stories/src/rawFluxDataTable.stories.tsx
- stories/src/tableGraph.stories.tsx
Closes #296 
Clean-up minor issues in Gauge.
> chore: turn off undesired property and behaviors for Gauge

- giraffe/src/components/ScatterLayer.tsx
- giraffe/src/transforms/scatter.ts
- stories/src/customScatter.stories.tsx
- stories/src/index.stories.tsx
- stories/src/linegraph.stories.tsx
- stories/src/scatterplot.stories.tsx
> Scatter plot stories for static and custom CSV's

- stories/src/data/geoLayer.ts
- yarn.lock
https://github.com/influxdata/giraffe/pull/280 left out committing yarn.lock changes.
And also fix merge conflicts from the api change to `addColumn`
> chore: update yarn.lock

- giraffe/README.md
- adds defaults for gauge layer configuration
- updates italics style for text regarding defaults
> chore: update README

- giraffe/src/components/TooltipStyles.ts
Guard against lack of colors in tooltip data
> fix: check for lack of colors in tooltip data

- giraffe/README.md
Updates the README with the changes in #317
> chore: update README to document legendColorizeRows

- giraffe/package.json
- giraffe/webpack.config.js
Closes #325
This allows proper importing via `<script>` tags.
> fix: webpack points to proper react external library

- giraffe/src/constants/index.ts
- giraffe/src/utils/useTooltipStyle.ts
> fix: increase tooltip z-index to be visible with all clockface components

- giraffe/README.md
Closes #323
Fills out the quickstart and makes it a little more of an easier experience.
Tested with https://dillinger.io/. Just paste the raw markdown readme file to see a rendered preview.
> docs: update the quickstart

- giraffe/package.json
- giraffe/src/components/geo/processing/PivotedGeoTable.ts
- giraffe/src/components/geo/processing/tableProcessing.ts
- giraffe/src/utils/fromFlux.ts
- giraffe/webpack.config.js
- yarn.lock
> refactor: remove lodash functions

- stories/.storybook/webpack.config.js
> test: add sourcemaps to stories so you can get a better sense of what broke

- stories/src/geo.stories.tsx
> Add Custom CSV story for pointMap

- giraffe/src/components/Geo.tsx
> Add ability to update lat long based on table data

- giraffe/src/components/Tooltip.tsx
- giraffe/src/types/index.ts
- stories/src/helpers.tsx
- stories/src/index.stories.tsx
We return null for the tooltip if it is disabled
> feat: allow tooltip disable

- giraffe/src/components/SizedPlot.test.tsx
- giraffe/src/components/SizedPlot.tsx
- giraffe/src/types/index.ts
- stories/src/annotation.stories.tsx
> feat: add hover interaction. add x and y domain values to callback args

- .prettierignore
- giraffe/README.md
- stories/src/annotation.stories.tsx
- stories/src/snapshotTests.stories.tsx
Addresses several issues in #422 
Closes issues **a, d, f, g, h, i**
> chore: update README and TypeScript error in Annotation storybook

- stories/.storybook/config.js
- stories/package.json
- yarn.lock
We have axios in two places, one is inside storybook-chromatic, which has been depreciated, lets see if upgrading this axios fixes the security issue. If we have to upgrade both that will be a separate PR
> fix: upgrade axios

- giraffe/README.md
- giraffe/src/index.ts
> feat: add README explanation for AnnotationLayerConfig and export the interface

- giraffe/src/components/Tooltip.tsx
> feat: Makes Tooltip disabled when empty array passed to legendColumn

- examples/Listing_of_giraffe_samples.md
Dependent on previous PR for css/scss changes to webpack.
> docs: added sample code for HTML page rendering and Table Plot type

- giraffe/src/index.ts
We would like to export `getLatestValues` and `formatStatValue` so that we can use them in the UI.
> feat: export getLatestValues and formatStatValue

- giraffe/src/components/AnnotationTooltip.tsx
> fix: typo fixed for AnnotationTooltip test ID

- giraffe/README.md
> Add geo plot configuration to Giraffe README

- giraffe/README.md
> docs: adding the time formatter docs

- giraffe/package.json
- giraffe/src/components/BandHoverLayer.tsx
- giraffe/src/components/StaticLegendBox.tsx
- giraffe/src/transforms/band.ts
- giraffe/src/types/index.ts
- giraffe/src/utils/PlotEnv.ts
- giraffe/src/utils/isVoid.ts
- giraffe/src/utils/legend/band.ts
- giraffe/src/utils/legend/sort.test.ts
- giraffe/src/utils/legend/sort.ts
- giraffe/src/utils/legend/staticLegend.test.ts
- giraffe/src/utils/legend/staticLegend.ts
- giraffe/src/utils/legend/tooltip.test.ts
- giraffe/src/utils/legend/tooltip.ts
- stories/src/staticLegend.stories.tsx
> feat: implement Band Plot's static legend

- stories/src/data/nflCSV.tsx
- stories/src/mosaic.stories.tsx
Adds another example to Mosaic
> chore: add another mosaic example and data to storybook

- giraffe/package.json
- giraffe/src/components/StaticLegendBox.tsx
- giraffe/src/constants/index.ts
> fix: allow legendOpacity to affect staticLegend.opacity

- giraffe/package.json
- giraffe/src/index.ts
export the constants for the columnKeys
> feat: export columnKeys as constants

- examples/Listing_of_giraffe_samples.md
This is the sample app for Giraffe mosaic graph
> added mosaic sample giraffe app

- giraffe/package.json
- giraffe/src/components/Brush.tsx
- giraffe/src/components/SizedPlot.tsx
- giraffe/src/utils/useDragEvent.ts
now only executing interactionaction onXBrush when the shift key is down
> feat: brush control keys shift

- giraffe/package.json
- yarn.lock
very simple.
not bumping the version number since I'll be doing another pr  for annotations and will bump it then.
> chore: adding pretty-quick

- giraffe/package.json
- giraffe/src/utils/geo.ts
Fixes the tooltip from saying color to properties.Colorfield  by removing the hard coded color value
> Fix: tooltip maps

- giraffe/package.json
- giraffe/webpack.common.config.js
- giraffe/webpack.dev.config.js
- giraffe/webpack.prod.config.js
Creates a webpack dev config, which required a common and prod config to also exist
> chore: add webpack dev, prod, and common configs

- giraffe/src/components/geo/processing/mixins.ts
- giraffe/src/utils/geo.test.ts
- giraffe/src/utils/geo.ts
Closes #579 
Adding tests around all the maps/geo utils with different use cases
> test: geo utils

- .eslintrc.json
No rule changes, only alphabetization.
> chore: alphabetize eslintrc entries

- giraffe/package.json
- giraffe/src/components/AnnotationLine.tsx
- stories/package.json
Adds a className for easy targeting in tests
> fix: add className to all annotation pins

- giraffe/package.json
- package.json
- stories/package.json
- yarn.lock
Force storybook to resolve to immer 9.0.6
> chore: force immer 9.0.6+ via yarn resolution

- giraffe/package.json
- giraffe/src/index.ts
- stories/package.json
Closes: https://github.com/influxdata/giraffe/issues/717
> feat: export getNominalColorScale to use in UI

- giraffe/package.json
- stories/package.json
Updates version number to publish https://github.com/influxdata/giraffe/pull/716
> chore: publish tooltip positioning fix

- giraffe/README.md
> fix: update external link to stacked line graph's definition

- giraffe/src/constants/singleStatStyles.ts
https://user-images.githubusercontent.com/106361125/172245521-e725ffac-332c-416a-935e-8ff985bed119.mov
> fix: text cursor while hovering over stat

- giraffe/package.json
- giraffe/src/components/SimpleTable/InnerTable.tsx
- giraffe/src/components/SimpleTable/PagedTable.tsx
- giraffe/src/style/variables.scss
- stories/package.json
- yarn.lock
- Matches the changes found here: https://github.com/influxdata/ui/pull/5257  
- Adds missing classnames for a couple of components  
- Updates `react-virtualized-auto-sizer` to the latest and greatest  
- Change `cf-form-md-font`, `cf-form-md-height`, `cf-form-md-padding` to be consistent with Clockface
> chore: add more updates to SimpleTable and subcomponents

- giraffe/package.json
- giraffe/src/components/RawFluxDataTable/RawFluxDataGrid.scss
- giraffe/src/components/Table/TableGraphs.scss
- giraffe/src/style/variables.scss
- stories/package.json
- stories/src/rawFluxDataTable.stories.tsx
> fix: update font color for RawFluxDataTable to make it visible

- giraffe/package.json
- giraffe/src/components/SimpleTable/PagedTable.tsx
- giraffe/src/components/SimpleTable/SimpleTableGraph.tsx
- giraffe/src/components/SimpleTable/SimpleTableLayer.tsx
- stories/package.json
Closes #806  
Ongoing effort for #805  
Here is a video showing the data set being updated and then paginating correctly. Also, the large data set renders well.
https://user-images.githubusercontent.com/10736577/191131202-a8e38677-e94e-4e8c-ba6c-2a92f96c583d.mp4
> feat: memoize SimpleTableLayer and clean up its hooks

- package.json
- yarn.lock
* chore: use ^1.7.3 for shell-quote rather than exact version in resolution
* chore: use resolution to resolve minimatch
> chore: use resolution to resolve minimatch
