influxdata/giraffe

src/index.ts
src/stats/bin.test.ts
src/stats/bin.ts
src/types/index.ts
src/utils/appendGroupCol.ts
src/utils/fluxToTable.test.ts
src/utils/fluxToTable.ts
src/utils/getNumericColumn.ts
src/utils/isNumeric.ts
src/utils/table.test.ts
stories/data.ts

Previously we had three different types of possible number columns: `uint`, `int`, and `float`, though the corresponding `data` for each type of column was always of type `number[]`. The motivation for the multiple number types was to be able to efficiently store numeric data as typed arrays, and to provide different default formatting based on the type of number. 
We haven't leveraged these opportunities yet, and it's not clear that we ever will. In the meantime, the multiple number types just add complexity.

Simplify column types

---

src/components/Axes.tsx
src/constants/index.ts
src/utils/PlotEnv.test.ts
src/utils/PlotEnv.ts
stories/snapshotTests.stories.tsx

Lines in line layers were being clipped under the following conditions:
- Non-HiDPI screen
- Line layer with a `lineWidth` setting of 1
- With data containing successive minimum or maximum values
This seemed to be caused by antialiasing.
This commit adds 1 `lineWidth` of padding to the edges of the plots to avoid the issue.
Closes #51

Fix clipping issue in line layers

---

src/components/ScatterLayer.tsx
src/utils/drawShapes.ts
src/utils/getSymbolScale.ts

Add tritip, hollow square, ex, and plus to scatter plot shapes
correct the placement of the circle.

Add new shapes to scatter repertoire

---

src/utils/getTimeFormatter.ts

Date.prototype.getDay() OBVIOUSLY returns the day of the week.
Date.prototype.getDate() returns the actual day of the month.
gah.
Closes https://github.com/influxdata/vis/issues/55

Convert getDay to getDate

---

src/utils/newTable.ts

Previously getColumn would throw an error if column specified did not exist or was not of type specified.
Closes https://github.com/influxdata/vis/issues/68

Return null if getColumn can not find column

---

src/utils/drawShapes.ts

I noticed scatter plot performance downgrading. 
Found this: 
https://stackoverflow.com/questions/28534715/why-does-filling-in-a-rectangle-on-a-canvas-degrade-performance-slowly
verified perf improvement in devtools.

Add begin path to each square draw to improve scatter performance

---

src/utils/PlotEnv.ts
src/utils/getLinearScale.ts
src/utils/lineData.ts
src/utils/useChangedDepsLogger.ts
stories/sin.stories.tsx
stories/sin.ts

The line layer was being re-rendered on every hover event, due to a bug in the memoization of the x and y scales.
Also adds a story for experimenting with large datasets. The following plot has 5 series with 200,000 points each:
The size of the dataset can be changed by tweaking the parameters in `stories/sin.ts`.

Fix unnecessary line layer renders

---

package.json
src/utils/formatters.test.ts
src/utils/formatters.ts
tsconfig.json
yarn.lock

Adds support for constructing time formatters using a format string:
```
import {timeFormatter} from '@influxdata/giraffe'
const f = timeFormatter({format: 'YYYY-MM-DD HH:mm Z', timeZone: 'UTC'})
f(new Date(0)) // => "1970-01-01 00:00 UTC"
```
Pulls in [intl-dateformat](https://github.com/zapier/intl-dateformat), a small library, to help accomplish this. 
Closes #95

Add format string support for formatting dates

---

src/components/Axes.tsx
src/components/Brush.tsx
src/components/LineHoverLayer.tsx
src/components/LineLayer.tsx
src/components/Plot.tsx
src/components/RectLayer.tsx
src/components/ScatterHoverLayer.tsx
src/components/ScatterLayer.tsx
src/components/SizedPlot.tsx
src/components/Tooltip.tsx
src/types/index.ts
src/utils/PlotEnv.ts
src/utils/brush.ts
src/utils/formatters.test.ts
src/utils/formatters.ts
src/utils/useDragEvent.ts
stories/customLayer.stories.tsx
stories/snapshotTests.stories.tsx

This PR adds a few small features to giraffe to facilitate https://github.com/influxdata/influxdb/pull/14347.
I took the opportunity to clean up the brush event handling code, which was confusing.
I also added the `displayName` prop to all components. This makes them show up with nice names in the React devtools, even when the actual function component names have been mangled by terser (e.g. show `SizedPlot` instead of `n`).
It might be easiest to review commit by commit.

Add custom layer support

---

src/utils/tooltip.ts

Fixes an issue where a plot would crash if the tooltip attempting to format void values.
Connect influxdata/influxdb#14436

Fix tooltip crash

---

giraffe/src/utils/useHoverPointIndices.ts

Layer legends were visible event when mouse y position was past the height of the canvas. 
With this, hover actions will not be active when mouseY > height.

Mouse position should be aware of y position just like x position

---

giraffe/src/utils/formatters.ts
stories/package.json

Closes #15808:
https://github.com/influxdata/influxdb/issues/15808
The default statement for formatting the date/time in giraffe is based on US 12h timezones. When users from countries that have a 24h based system access giraffe, their timezone is undefined.
Updated default format to be the 24h system. This is a patch solution until a new feature is implemented that allows users to specify their display time preferences

fix(undefined-timezone): fixed issue where 24h time formats were displaying undefined timezones

---

giraffe/package.json
giraffe/src/components/LineHoverLayer.tsx
giraffe/src/transforms/line.test.ts
giraffe/src/transforms/line.ts
giraffe/src/types/index.ts
giraffe/src/utils/PlotEnv.ts
giraffe/src/utils/getLineHoverPoints.ts
giraffe/src/utils/lineData.test.ts
giraffe/src/utils/lineData.ts
giraffe/src/utils/tooltip.ts
package.json
stories/package.json
stories/src/customLayer.stories.tsx
stories/src/data/cpu.ts
stories/src/data/stackedLineLayer.ts
stories/src/helpers.tsx
stories/src/index.stories.tsx
stories/src/snapshotTests.stories.tsx

Closes https://github.com/influxdata/giraffe/issues/43

feat: add option for stacked line layers

---

giraffe/src/index.ts

In order to use LinePosition, we need to export it

feat: export LinePosition as a type

---

giraffe/src/utils/formatters.ts

Currently passing in a custom formatted time into the `formatTime` function will error out if a flag for `a` (am/pm) is passed in the time format 
Added a custom check for whether the formatted time includes an `a` and resorts to forcing the format to set the times to 12h with `am/pm`

feat(formatTime): added in capacity to output am/pm in custom formats

---

giraffe/src/utils/formatters.test.ts
giraffe/src/utils/formatters.ts

Closes https://github.com/influxdata/influxdb/issues/16122
Updates 12-hour time format to remove leading zeros.

fix: remove leading zero from 12-hour format

---

giraffe/src/constants/index.ts
giraffe/src/types/index.ts
giraffe/src/utils/PlotEnv.ts
giraffe/src/utils/getLogScale.ts
giraffe/src/utils/getScale.ts
stories/package.json
stories/src/helpers.tsx
stories/src/index.stories.tsx
yarn.lock

Closes: #12 
X and Y Scale can now be updated to be either linear or logarithmic.
Typically, switching to log scale is in response to skewness towards large values.

feat(giraffe): add log scale type

---

giraffe/src/index.ts

Will help with closing https://github.com/influxdata/influxdb/issues/16111
By exposing the `lineTransform` and `getDomainDataFromLines` methods, we allow consumers to create a flattened line spec in exactly the same way that giraffe does it. This will lead to consistency when we determine the `extent` and `domain` from a set of data without re-implementing the same solution externally.

fix: expose line transformation for external use

---

giraffe/src/index.ts
giraffe/src/utils/lineData.ts

Additional export needed for https://github.com/influxdata/influxdb/issues/16111
This also fixes the type for `getDomainDataFromLines`

fix: export DomainLabel and fix type

---

giraffe/src/utils/PlotEnv.ts
giraffe/src/utils/__mocks__/getTextMetrics.ts
giraffe/src/utils/getTicks.test.ts
giraffe/src/utils/getTicks.ts
stories/src/index.stories.tsx

Closes https://github.com/influxdata/giraffe/issues/135 and https://github.com/influxdata/influxdb/issues/16395
Instead of using 'W' for the average character width, we measure the exact width of the label. Then we ask d3 to give us as many time ticks as will fit on the x-axis with the following restrictions to act as padding around the labels:
- round down when finding the maximum number as the first suggestion to d3
- four or more labels: the sum of all the lengths of the labels is shorter than the available space by at least one label's length
- less than four labels: 0.25, 0.50, 0.75 label length as spacing for one, two, and three labels respectively

fix: use as many time ticks as d3 can fit on the x-axis

---

giraffe/src/components/LineLayer.tsx
giraffe/src/constants/columnKeys.ts
giraffe/src/utils/fixtures/tooltip.ts
giraffe/src/utils/tooltip.test.ts
giraffe/src/utils/tooltip.ts
stories/src/data/stackedLineLayer.ts
stories/src/index.stories.tsx

Closes https://github.com/influxdata/influxdb/issues/16489 and https://github.com/influxdata/giraffe/issues/145
**Stacked Line Graphs**
- Fixes the data for the hovered points when lines intersect (have similar values)
- Sorts the order of the rows in the tooltip to match the order of the hovered points
- Adds a column in the tooltip to make it clear how many lines are represented in each row
- Adds unit tests for the tooltip utility

fix: Use correct scale when hovering over stacked line graphs

---

giraffe/src/utils/tooltip.test.ts
giraffe/src/utils/tooltip.ts

Closes https://github.com/influxdata/influxdb/issues/16489 (for real this time)
Actually show the columns in the tooltip by associating them to the correct column

fix: show the additional columns

---

giraffe/src/utils/tooltip.test.ts

More tests as part of https://github.com/influxdata/giraffe/issues/145
Adds more tests for tooltip colors. Consistent coloring is an effective way to ensure the data has been properly sorted and guards this functionality for future changes.

test: add more tests for tooltip colors

---

giraffe/src/constants/columnKeys.ts
giraffe/src/transforms/line.test.ts
giraffe/src/transforms/line.ts
giraffe/src/types/index.ts
giraffe/src/utils/tooltip.ts

Closes https://github.com/influxdata/giraffe/issues/158
By creating a map of all the time points, we can correctly track and add up cumulative values as the time points are traversed during line transformation

fix: calculate correct cumulative values for lines of different lengths

---

giraffe/src/utils/fixtures/tooltip.ts
giraffe/src/utils/tooltip.test.ts
giraffe/src/utils/tooltip.ts

Closes https://app.zenhub.com/workspaces/applicationmonitoring-5e3b05772922e316b3a210a4/issues/influxdata/influxdb/16984
Giraffe's sorting functionality was assuming that the lineData would exist, even though it was an option parameter
Added defaults to the lineData prop and return the default hover index if the lineData is empty. This was simply the most straightforward solution, but it could be that we would need to implement a more dynamic solution that handles sorting for scatter plots specifically since some of those properties do not exist

fix(ui): fixed tooltip bug that was causing giraffe to crash for scatterplots

---

giraffe/src/constants/columnKeys.ts
giraffe/src/types/index.ts
giraffe/src/utils/PlotEnv.ts
giraffe/src/utils/getTicks.test.ts
giraffe/src/utils/getTicks.ts
stories/src/index.stories.tsx

Closes https://app.zenhub.com/workspaces/applicationmonitoring-5e3b05772922e316b3a210a4/issues/influxdata/influxdb/17585
Separate the generation of vertical and horizontal ticks to allow different spacing. For each direction, ticks can be time ticks or value ticks.
x: time, y: value
y: time, x: value

fix: separate creation of horizontal and vertical ticks

---

giraffe/package.json
giraffe/src/components/SizedPlot.tsx
giraffe/src/types/index.ts
stories/package.json
stories/src/customLayer.stories.tsx

Closes #183 
- Following best practices, adds a unique key to the custom layer element in a list of React elements.
- Minor tweak to the `prettier` script to only fix files that we care about.

fix: add unique key to custom layer element

---

giraffe/src/transforms/heatmap.test.ts
giraffe/src/transforms/heatmap.ts

Closes https://github.com/influxdata/influxdb/issues/18182
In heatmap, use only reasonable numbers for bin count (the number of possible heat "blobs") on any axis so that they cannot be NaN, 0, negative, negative Infinity, or positive Infinity

fix: constrain bin count in heatmap to numbers that will not throw an error

---

giraffe/README.md
giraffe/package.json
giraffe/src/components/LatestValueTransform.tsx
giraffe/src/components/SingleStatLayer.tsx
giraffe/src/components/SizedPlot.tsx
giraffe/src/constants/singleStatStyles.ts
giraffe/src/index.ts
giraffe/src/types/index.ts
giraffe/src/utils/PlotEnv.ts
giraffe/src/utils/extrema.ts
giraffe/src/utils/fixtures/tooltip.ts
giraffe/src/utils/flatMap.ts
giraffe/src/utils/formatStatValue.test.ts
giraffe/src/utils/formatStatValue.ts
giraffe/src/utils/getJavaScriptTag.test.ts
giraffe/src/utils/getJavaScriptTag.ts
giraffe/src/utils/getLatestValues.test.ts
giraffe/src/utils/getLatestValues.ts
giraffe/src/utils/isNumber.test.ts
giraffe/src/utils/isNumber.ts
giraffe/src/utils/isString.test.ts
giraffe/src/utils/isString.ts
giraffe/src/utils/preventNegativeZero.test.ts
giraffe/src/utils/preventNegativeZero.ts
giraffe/src/utils/range.test.ts
giraffe/src/utils/range.ts
giraffe/src/utils/tooltip.test.ts
stories/src/customLayer.stories.tsx
stories/src/data/singleStatLayer.ts
stories/src/index.stories.tsx

Closes #169 
Adds Single Stat as a custom layer
Single Stat by itself
Single Stat with line graph
Single Stat at maximum decimal places with line graph

feat: add Single Stat as a custom layer

---

stories/src/customLayer.stories.tsx
stories/src/index.stories.tsx

Demonstrates Single Stat's new superhero powers:
- controls its own size
- controls its own position
When combined with a line graph, they become the Avengers.

chore: add sizing and positioning to Single Stat stories

---

stories/package.json

Updates the version of this page: https://influxdata.github.io/giraffe
to match the published release

chore: update demo page version to match release

---

README.md
giraffe/README.md

Point users to the demo page without requiring them to run Storybook locally.

chore: add links to the Storybook demos

---

giraffe/src/utils/formatters.test.ts
giraffe/src/utils/formatters.ts

Closes https://github.com/influxdata/influxdb/issues/18458
Meridiem time should be case insensitive.

fix: allow meridiem time format to be case insensitive

---

giraffe/package.json
giraffe/rollup.config.js
yarn.lock

Preemptively update rollup and plugins to prevent the "module is not defined" error that occurs when importing certain external dependencies during rollup build.

chore: update rollup and plugins

---

giraffe/src/components/BandLayer.tsx
giraffe/src/utils/getBandHoverIndices.test.ts
giraffe/src/utils/getBandHoverIndices.ts
stories/src/band.stories.tsx

When line data has different lengths, Band Chart should correctly calculate the hovered indices of the hovered points

fix: determine correct hover indices when line lengths are different

---

giraffe/src/utils/fromFlux.test.ts
giraffe/src/utils/fromFlux.ts

The purpose of this PR is to update the fromFlux parser in Giraffe in order to return a formatted `Schema` of the data being returned. This Schema is the basis for the in-progress Query Builder that is being integrated into Flows on the influxDB UI.
The reason that we are updating the `fromFlux` parser in Giraffe rather than creating a new flux parser is in order to reduce the eventual drift that may occur in having multiple parsers in multiple repos. 
The reason we need the flux results returned in a specific way is so that the UI can accurately map query results in a way that is accessible and predictable for the UI when mapping out the new query builder. This work is related to the current work in progress that can be found here:
https://github.com/influxdata/influxdb/pull/19450

feat(schema-parser): updated fromFlux to return formatted schema when parsing data

---

giraffe/src/index.ts
giraffe/src/types/index.ts
giraffe/src/utils/fromFlux.ts

This PR is meant to clean up the TS issues and general bad practices of not localizing types by moving the newly declared Schema, TagValues and Tag interfaces into the `src/types` directory. This PR also removes the `Measurement` type since it is not being used

fix(types): moved types into the right location and imported into fromFlux

---

giraffe/src/index.ts
giraffe/src/types/index.ts
giraffe/src/utils/fromFlux.test.ts
giraffe/src/utils/fromFlux.ts

This PR resolves the issue that stemmed from the new parser addition by doing two things:  
- Keeping the new additions in a separate parser that should replace the existing one once proven stable
- Updated some of the schema building logic in order to reduce nested loops
The issue that the created can be found here:
https://github.com/influxdata/idpe/issues/8467
The issue primarily stemmed from here:
https://github.com/influxdata/giraffe/compare/fix/fromFlux?expand=1#diff-2386bd719c19aac4f8ff42434a17cd08L271-L278
By changing the datatype and reducing the nested looping that was previously taking place, I was able to ensure that data is parsed correctly and efficiently, with a max parsing differential of ~7s using a 27mb data set based on the raw data output by the issue linked above

fix(fromFlux): flagging the fromFlux as a separate version to integrate into the UI

---

giraffe/src/utils/fromFlux.ts

Not entirely sure if this resolves the issue I'm currently seeing in the UI, but it does resolve a potential bug in the future that was setting the existing tags as an empty set in the event that it didn't exist rather than an empty object.

potentially fixes the issue for the parser

---

giraffe/src/utils/formatters.test.ts
giraffe/src/utils/formatters.ts
stories/src/csv.stories.tsx

Closes idpe #8310
Prevents 24-hour and UTC format without "a" from displaying "24" for the hours

fix: prevent 24-hour and UTC format from displaying "24" for the hours

---

giraffe/README.md
giraffe/src/components/BandHoverLayer.tsx
giraffe/src/components/BandLayer.tsx
giraffe/src/types/index.ts
giraffe/src/utils/PlotEnv.ts
stories/src/band.stories.tsx

Part of idpe 8337
As part of saving BandViewProperties for dashboards, a "mainColumn" property was added to keep track of the primary line in Band Plot. To keep Giraffe's api easy to use and match up with similar properties in Cloud 2 and OSS, "name" should be called "mainColumnName". For reference, here are the back-end changes:
https://github.com/influxdata/idpe/pull/8559
https://github.com/influxdata/influxdb/pull/19550

feat: change "name" to "mainColumnName" for the primary line of Band Plot

---

giraffe/README.md
giraffe/src/components/Tooltip.tsx
giraffe/src/constants/index.ts
giraffe/src/types/index.ts
stories/src/band.stories.tsx
stories/src/index.stories.tsx

Closes https://github.com/influxdata/influxdb/issues/17227
As part of adjusting the Tooltip's columns, we allow the user to set the opacity of the tooltip so that large tooltips can be useful while still allowing visibility to the graph underneath.
Here is an example of opacity set to 0.5 (half)

feat: add legendOpacity to the Tooltip

---

giraffe/src/index.ts

This PR adds GetColumn as an exported interface

chore(getColumn): export GetColumn interface

---

giraffe/src/types/index.ts
giraffe/src/utils/fromFlux.ts

This PR repairs type definitions to match the implementation
* Table type changed to match SimpleTable implementation
* Column type changed to match existing test `parses empty numeric values as null` defined in `fromFlux.test.ts`
These changes were discovered during the optimized integration of influxdb-client-js and giraffe.

fix(types): repair Table and Column type to match implementation

---

giraffe/src/utils/formatStatValue.test.ts
giraffe/src/utils/formatStatValue.ts

Closes #295 
Allows large numbers that end with decimal 0 to have numeric separators.

fix: use separator for large numbers

---

README.md
giraffe/README.md
giraffe/src/index.ts
giraffe/src/transforms/band.ts
giraffe/src/transforms/heatmap.test.ts
giraffe/src/transforms/heatmap.ts
giraffe/src/transforms/histogram.test.ts
giraffe/src/transforms/histogram.ts
giraffe/src/transforms/line.ts
giraffe/src/transforms/mosaic.ts
giraffe/src/transforms/scatter.ts
giraffe/src/types/index.ts
giraffe/src/utils/PlotEnv.test.ts
giraffe/src/utils/fixtures/tooltip.ts
giraffe/src/utils/fromFlux.test.ts
giraffe/src/utils/fromFlux.ts
giraffe/src/utils/fromRows.ts
giraffe/src/utils/getLatestValues.test.ts
giraffe/src/utils/newTable.ts
giraffe/src/utils/tooltip.test.ts
stories/src/data/bandLayer.ts
stories/src/data/cpu.ts
stories/src/data/cpuString.ts
stories/src/data/gaugeLayer.ts
stories/src/data/mosaicDataSet.ts
stories/src/data/singleStatLayer.ts
stories/src/data/stackedLineLayer.ts
stories/src/sin.ts
stories/src/snapshotTests.stories.tsx

Closes https://github.com/influxdata/ui/issues/123
SimpleTable converts the original data type for integers. By losing out on this context, the raw CSV view cannot properly map results based on the CSV string that's returned.
Updated the SimpleTable class to include a reference to the originalType in each column. Added a method to the class in order to retrieve the relevant data when needed. After having some brief discussions with @drdelambre I added a default `system` type that is being set as the originalType whenever Giraffe sets a default `number` type since there is no concrete way of knowing whether the actual type is a `long`, `double`, or `unsignedLong`

feat(fromFlux-original-type): added a reference to the original dataType in SimpleTable

---

giraffe/src/components/GaugeLayer.tsx
giraffe/src/types/index.ts

Gauge config parameters has default argument (are now optional):
` prefix, suffix, tickPrefix, tickSuffix ` has now default value `''`
`decimalPlaces` has now default value `{}`
When using `gaugeTheme` all parameters are optional. Missing parameters is filled in with default theme (already was implemented; only missing in interface - definition changed to be more user-friendly)

feat: gauge default config

---

giraffe/src/components/BandHoverLayer.tsx
giraffe/src/components/BandLayer.tsx
giraffe/src/transforms/band.test.ts
giraffe/src/transforms/band.ts
giraffe/src/utils/drawBands.ts
giraffe/src/utils/getBandHoverPoints.ts

Closes #277 ...for real this time
Fixes Band Plot's color scaling on hover, closing the latest point in this issue.

fix: use color scaling consistently across all aspects of Band Plot

---

.circleci/config.yml
.gitignore
giraffe/jest.config.js

Closes #139 
Uploads a `coverage/index.html` to our CircleCI test artifacts tab.  It looks a little something like this:

test: add coverage to test artifacts

---

giraffe/rollup.config.js

In reference to https://github.com/influxdata/giraffe/pull/282#issuecomment-706004339
Let's set this for anyone who might be using influxdb-client-js with giraffe. Keeping this outside of the scope of the PR it came from, since it might be helpful as a standalone change.

feat: use browser option in rollup config

---

giraffe/src/components/LineHoverLayer.tsx
giraffe/src/components/LineLayer.tsx
giraffe/src/transforms/line.ts
giraffe/src/types/index.ts
giraffe/src/utils/fixtures/line.ts
giraffe/src/utils/getLineHoverPoints.ts
giraffe/src/utils/lineData.perf.test.ts
giraffe/src/utils/lineData.ts
giraffe/src/utils/tooltip.test.ts
giraffe/src/utils/tooltip.ts

Closes https://github.com/influxdata/influxdb/issues/18179
- avoid using Array.prototype.concat to repeatedly re-create arrays in a loop
- call `getDomainDataFromLines` only once internally during transformation and save it on the `spec`
- test `getDomainDataFromLines` and `lineTransform` with 5,000,000 data points to ensure error will not be thrown

fix: make getDomainDataFromLines performant

---

giraffe/src/components/Tooltip.tsx
giraffe/src/components/TooltipStyles.ts
giraffe/src/constants/colorSchemes.ts
giraffe/src/constants/index.ts
giraffe/src/types/index.ts
stories/src/band.stories.tsx
stories/src/helpers.tsx
stories/src/index.stories.tsx
stories/src/linegraph.stories.tsx
stories/src/scatterplot.stories.tsx

- Make background of tooltip darker
- Make font weight of text in tooltip slightly bolder
- Add a handful of color schemes optimized for less series
- Add `legendColorizeRows` option with default `true`
- If `false` colors are displayed as dots in each row instead of applied to text
- Since we are generating CSS dynamically and the style functions make the component a bit hard to read I moved them to a separate file named `TooltipStyles.ts`
- the `___Styles.ts` naming scheme is probably something we could re-use for other components
- The styles file exports only 1 function which returns an object containing styles for every element organized by element name

Improve Legibility of Tooltip

---

giraffe/src/utils/fromFlux.test.ts
giraffe/src/utils/fromFlux.ts

Closes #314 
At various points in the fromFlux parser, assertions were throwing unhandled errors, leading to the UI crashing in a number of different scenarios. Since fromFlux is the primary parser (at this point in time), it is important that it handles errors in a way that does not prevent users from reaching an unusable state
Since most of the pain points were already being handled by the parser, wrapping the more nuanced logic in a try/catch and returning the error to the user allows the parser to degrade gracefully when an error is thrown.
With this change comes a change to the type definition to allow for the error to be handled by the UI in the event that an error is thrown.
Finally, some of the variable assignments were moved outside of the for loop in order to reduce memory …

feat(fromFlux-error-handling): optimized fromFlux, fromFluxWithSchema, and added error handling for both

---

giraffe/src/utils/formatters.ts

This is needed to fix the differences in formatting, by allowing no formatting

fix: formatters allow for no formatting

---

giraffe/README.md
giraffe/src/types/index.ts
giraffe/src/utils/PlotEnv.ts
giraffe/src/utils/getTextMetrics.ts
giraffe/src/utils/getTicks.test.ts
giraffe/src/utils/getTicks.ts
giraffe/src/utils/isFiniteNumber.test.ts
giraffe/src/utils/isFiniteNumber.ts
stories/src/data/randomTable.ts
stories/src/linegraph.stories.tsx

Closes #79 
Allows user to specify tick generation in the config.

feat: allow ticks to be configurable with total count, interval, and starting placement

---

giraffe/package.json
giraffe/src/transforms/heatmap.test.ts
giraffe/src/transforms/histogram.test.ts
giraffe/src/transforms/index.test.ts
giraffe/src/utils/PlotEnv.test.ts
giraffe/src/utils/fluxParsing.test.ts
giraffe/src/utils/formatStatValue.test.ts
giraffe/src/utils/formatters.test.ts
giraffe/src/utils/fromFlux.test.ts
giraffe/src/utils/fromRows.test.ts
giraffe/src/utils/getJavaScriptTag.test.ts
giraffe/src/utils/getLatestValues.test.ts
giraffe/src/utils/identityMerge.test.ts
giraffe/src/utils/isNumber.test.ts
giraffe/src/utils/isString.test.ts
giraffe/src/utils/isSymbol.test.ts
giraffe/src/utils/lineData.perf.test.ts
giraffe/src/utils/range.test.ts
giraffe/src/utils/rawFluxDataTable.test.ts

- `test` becomes `it`
- collect coverage stats in test scripts to view them locally

chore: rename test to it and add collectCoverage option to test scripts

---

giraffe/src/utils/getTicks.test.ts
giraffe/src/utils/getTicks.ts

Part of #79 
`generateTicks` should actually generate ticks when the tick start is outside of the domain and the tick step brings any generated ticks within the domain.

fix: reconcile generateTicks with the documented behavior in the README

---

README.md
giraffe/README.md

Better scaling without the extra padding on the side.

chore: use the 339x400 logo

---

giraffe/webpack.config.js

The previous fix worked for `<script>` imports, but left common imports high and dry. Looks like we'll need a bit more config.

fix: bundle react correctly as an external dependency

---

giraffe/package.json
giraffe/webpack.config.js

this should fix `<script>` consumption of Giraffe.
`v0.43.0` changed the only usage of `react-dom` in the Giraffe library, and the default config caused pages that imported Giraffe via `script` tags to break.

chore: update webpack external config for react-dom

---

giraffe/src/constants/index.ts
giraffe/src/utils/getTicks.ts

Closes #362 
1000 seems like a reasonable limit. This might seem a little bit high but I wanted to leave some wiggle room for any users who might display their graphs on very large screens (a stadium-sized projector) with a small font. Not sure if there would ever be such a use case.
Performance is great with 1000 as the limit. Tested with the existing storybook story on user defined ticks.
I am open to feedback on this number and willing to adjust accordingly.

fix: limit tick generation to 1000 ticks

---

giraffe/src/utils/getTextMetrics.ts

Closes #363 
Look for more skinny characters when updating the the sample text that determines axis padding. This will improve readability and prevent axis tick labels from being cut off on the y-axis.

fix: update the size of the sample text that determines axis padding

---

giraffe/README.md

docs: update quickstart to make it clear react and node aren't required

---

giraffe/README.md
giraffe/src/components/LineLayer.tsx
giraffe/src/constants/index.ts
giraffe/src/utils/useHoverPointIndices.ts

Closes idpe 9107
When there are many (thousands+) of data points with the same timestamp, hovering over them causes the browser to throw an error - "RangeError: maximum call stack size exceeded". What happens is, Giraffe collates the data of all of the nearest points to the mouse position. And then tries to render all of these points in the legend. When there are too many points, rendering all of these points on update causes this error.
To fix this, we limit the count of the nearest points to the first 200 points. This number was chosen because, visually, the legend won't fit 200 points in typically-used font sizes. Vertically, a laptop screen fits around 60 - 70 rows using a 12px font. So, 200 should be a sufficiently high limit. We can adjust this limit as necessary.
This is a …

fix: limit current hover point's nearest points to the first 200 data points

---

stories/src/data/randomTable.ts

* moves arrays that were defined in a closure to inside the function now.
* what was happening was the closure was keeping the same set of arrays around and overwriting them, making it impossible to call `randomTable` subsequently to get unique tables.
* adds ability to override the number of records and the records per row

chore: update randomTable to allow subsequent calls

---

giraffe/src/components/BandLayer.tsx
giraffe/src/transforms/band.test.ts
giraffe/src/transforms/band.ts
giraffe/src/types/index.ts
giraffe/src/utils/drawBands.ts
giraffe/src/utils/getBandHoverIndices.test.ts
giraffe/src/utils/getBandHoverIndices.ts
giraffe/src/utils/useBandHoverColumns.ts
stories/src/band.stories.tsx
stories/src/data/bandCSV.ts

Closes idpe 9144
Band chart was doing strange things with the hover dimensions. In any flux CSV response that comes from using "group by", the hover points become misaligned. To fix this:
- stop doing strange things with the hover dimensions
- define all of the hoverable points for Band chart and use that everywhere
- take advantage of having the line data aligned by band by looking up the corresponding upper and lower sections per band using a matching offset
- fix the aligning of line data by handling edge case where an "upper" or "lower" line is not associated with any "main" line
- memoize the calculation of the hoverable points to make hovering snappy and the user happy

fix: use correct dimensions and hoverable points for Band Plot and untangle unnecessary code

---

stories/.storybook/webpack.config.js

This will let you comment out variable usage without having to comment out declarations when you're writing or testing stories.

test: ignore 6133 declared but never read errors in stories

---

giraffe/src/components/Tooltip.tsx
giraffe/src/constants/index.ts
giraffe/src/utils/useHoverPointIndices.ts

Closes #394 
Previously, the limit on hover points was too low. It also did not scale with the size of the graph. Here is the fix.
- ~~increase the limit~~
- ~~scale the limit to account for width and height of the graph~~
- revert the limit because as currently implemented, the limit is a loss of data
- use a visual limit that is based on width, height, and legend orientation

fix: revert the bin limits on hover points and use a visual limit for the Tooltip

---

giraffe/package.json
giraffe/publish
package.json

Closes #395
```bash
~/Development/giraffe>yarn run publish
yarn run v1.22.4
$ echo 'To publish giraffe, run ./giraffe/publish $version'
To publish giraffe, run ./giraffe/publish $version
✨  Done in 0.06s.
```
```bash
~/Development/giraffe/giraffe>yarn run publish
yarn run v1.22.4
$ echo 'To publish giraffe, run ./publish $version'
To publish giraffe, run ./publish $version
✨  Done in 0.06s.
```
```bash
~/Development/giraffe/giraffe>./publish
Please specify a SemVer version to publish 'X.Y.Z(-PRERELEASE)(+BUILD)'
```
```bash
~/Development/giraffe/giraffe>./publish yeah-buddy
The version needs to follow a SemVer naming scheme 'X.Y.Z(-PRERELEASE)(+BUILD)'
~/Development/giraffe/giraffe>./publish 1.23
The version needs to follow a SemVer naming scheme 'X.Y.Z(-PRERELEASE)(+BUILD)' …
```

feat(publish): add confirmation to publish script, add more error messaging

---

giraffe/jest.config.js
giraffe/package.json
giraffe/src/components/SizedPlot.test.tsx
giraffe/src/components/SizedPlot.tsx
giraffe/src/types/index.ts
giraffe/src/utils/PlotEnv.ts
stories/src/annotation.stories.tsx
yarn.lock

Closes #412
Adds (yet another) property to `Config`: 
```ts
interactionHandlers: InteractionHandler
```
`InteractionHandler` currently defines a single interaction, `doubleClick`. The current default behavior for doubleClick is to `resetDomains` which effectively unzooms the screen. When a consumer of `Plot` provides an `interactionHandler` callback for `doubleClick`, Giraffe sends back the following data:
`hoverX`: the x coordinate of the cursor when the double click happens
`hoverY`: the y coordinate of the cursor when the double click happens
`xDomain`: the x domain of the graph (i.e. the visible horizontal portion) when the double click happens
`yDomain`: the y domain of the graph (i.e. the visible vertical portion) when the double click happens
`resetDomains`: a function to reset the …

feat: add ability to override default interaction behavior

---

giraffe/src/components/AnnotationHoverLayer.tsx
giraffe/src/components/AnnotationLayer.tsx
giraffe/src/components/AnnotationTooltip.tsx
giraffe/src/components/Tooltip.tsx
giraffe/src/constants/index.ts
giraffe/src/transforms/annotation.test.ts
giraffe/src/transforms/annotation.ts
giraffe/src/types/index.ts
giraffe/src/utils/annotationData.ts
giraffe/src/utils/useTooltipElement.ts
giraffe/src/utils/useTooltipStyle.ts
stories/src/annotation.stories.tsx
stories/src/data/annotation.ts

Closes #400 
Notable interface change:
AnnotationMark previously used **"direction"** as the property name to indicate vertical (direction: 'x') or horizontal (direction: 'y'). This property name will change to **"dimension"** which is less confusing, more accurate, and consistent with the rest of the code.
Annotation tooltip, initial implementation:

feat: implement Annotation Tooltip

---

giraffe/package.json
giraffe/webpack.config.js
yarn.lock

This is the minimal configuration needed to get webpack correctly bundling leaflet CSS. We'll optimize the size of our bundle in the near future

Add style loader for react leaflet

---

giraffe/src/utils/identityMerge.ts

Fixing defect influxdata#434. Required by geo widget, possibly others as well.

fix #434 - configs should be read-only

---

giraffe/src/components/AnnotationLayer.tsx
giraffe/src/components/AnnotationLine.tsx
giraffe/src/components/AnnotationTooltip.tsx
giraffe/src/types/index.ts
giraffe/src/utils/annotationData.ts
giraffe/src/utils/useTooltipStyle.ts
stories/src/annotation.stories.tsx
stories/src/data/annotation.ts
stories/src/helpers.tsx

- Clamp position values on annotation lines and tooltips
- Using floats here will result in blurry rendering, so everything is rounded to a whole number
- Up for debate but IMO sharp rendering > extreme precision
- Add caret element to annotation tooltips
- Introduce `pin` option for annotations that controls which pin head element is rendered
- `circle` for single points in time
- `start` & `stop` for ranges
- `none` for... well none, duh
- Change default line width on annotations to `2` to increase legibility
- The existing `1` width seemed too faint and looked semi-transparent
`tooltip in y axis`
`tooltip in x axis`
`start`
`stop`
`circle`

feat: polish appearance of annotations

---

giraffe/src/components/SizedPlot.tsx

closes #453 
Tested using the docker changes Gene introduced.
1. checkout master
1. build
1. let ui hot reload
1. go [to this line in `XYPlot`](https://github.com/influxdata/ui/blob/master/src/shared/components/XYPlot.tsx#L233)
1. add this line somewhere: `console.log(plotInteraction.valueX)`
1. double click on the graph observe that it's the start of the domain
1. checkout `bucky_fix_incorrect_valueX`
1. wait for ui to hotreload
1. double click on the graph and observe the correct time

fix(hoverInteraction): use hoverEvent.x, not hoverX to report position of cursor

---

giraffe/src/utils/fromFlux.test.ts
giraffe/src/utils/fromFlux.ts

closes: #452 
Tested functionality using the CSV uploader in the UI with this csv:
```
#group,false,false,true,true,false,false,true,true,true,true
#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,double,string,string,string,string,dateTime:RFC3339,double
#default,last,,,,,,,,,,,
,result,table,_start,_stop,_time,_value,_field,_measurement,host,station_id,time2,numbbbber
,,0,2021-01-19T20:58:58.549310588Z,2021-01-21T20:58:58.549310588Z,2021-01-21T13:00:00Z,1,is_installed,baywheels,ip-192-168-1-6.ec2.internal,499, 2021-01-18T12:20:02.582Z ,44 ,
```

fix: fromFlux dateTime parsing

---

giraffe/package.json
yarn.lock

Updates ts-jest to remove this warning:
```ts-jest[versions] (WARN) Version 26.6.3 of jest installed has not been tested with ts-jest. If you're experiencing issues, consider using a supported version (>=24.0.0 <25.0.0). Please do not report issues in ts-jest if you are using unsupported versions.```

chore: update ts-jest to keep up with recent update to jest

---

giraffe/package.json
giraffe/src/components/Axes.tsx
giraffe/src/components/BandLayer.tsx
giraffe/src/components/LineLayer.tsx
giraffe/src/components/Plot.tsx
giraffe/src/components/RectLayer.tsx
giraffe/src/components/SizedPlot.test.tsx
giraffe/src/components/SizedPlot.tsx
giraffe/src/index.ts
giraffe/src/utils/exportImage.ts
stories/src/utilities.stories.tsx
yarn.lock

Closes #446
Adds `exportImage` to giraffe's exported interface. This takes in an axes canvas reference, and a layer reference, and produces a PNG bitmap of the graphs.
This currently only accepts a single canvas layer. I imagine we'll have to iterate on this.
This also adds stories for taking screenshots of the following graphs:
- line
- stacked line
- histogram
- heatmap
- band chart

feat: export graphs as PNG image

---

giraffe/src/components/Geo.tsx
giraffe/src/constants/index.ts
giraffe/src/utils/useTooltipStyle.ts

Funny story. I was doing some experimenting with loading Giraffe on the server using a minimal component configuration. And I just couldn't for the life of me understand why I was getting leaflet leaflet errors when I clearly didn't include any leaflet stuff.
I did some digging and it turns out - and this is just _hilarious_ - that some Geo code includes the entire Geo component structure to get a constant that's defined in the `Geo` component and only used in one file. 🙄

fix: don't import the entire damn geo component structure to get a value

---

giraffe/package.json
giraffe/src/components/SizedPlot.test.tsx
giraffe/src/components/SizedPlot.tsx
giraffe/src/types/index.ts

add singleClick to interactionHandlers, and make the SizedPlot respond to single; not doubleclicks

chore: use single, not double clicks for SizedPlot

---

giraffe/package.json
giraffe/src/index.ts
giraffe/src/utils/formatters.ts

As a follow-up to https://github.com/influxdata/ui/issues/768 and to allow consuming apps to improve time formatting, expose the options that are configurable.

chore: export the TimeFormatterFactoryOptions interface

---

examples/Listing_of_giraffe_samples.md

updates name and link to influx-client-js library
adds ISS Giraffe example

docs: updates giraffe examples doc

---

stories/.storybook/webpack.config.js

fix: remove webpack's compilerOptions.rootDir to allow renaming the repo when cloning

---

giraffe/package.json
giraffe/src/components/SizedPlot.test.tsx
giraffe/src/components/SizedPlot.tsx

Closes #507 
Brush behavior (click-dragging with the mouse) requires the user to release, which is considered a (long) single-click. Sized Plot was inadvertently resetting the domains right before the Brush behavior was applied. The steps described in #507 would be summarized as follows:
1. Start the zoom on x-axis by click-dragging
2. (Sized Plot resets all domains)
3. Release the click to complete the zoom
4. Brush behavior is applied on one dimension, the x-axis, and a new x-domain is set
--
5. Start the zoom on y-axis by click-dragging
6. (Sized Plot resets all domains --- OOPS! x-domain is now the original values before step 1)
7. Release the click to complete the zoom
8. Brush behavior is applied on one dimension, the y-axis, and a new y-domain is set
This is reproduceable with the …

fix: prevent resetting of domains when no interaction handlers are given

---

giraffe/package.json
giraffe/src/components/Geo.tsx
giraffe/src/components/geo/processing/tableProcessing.ts

Closes #513 
Improving Geo code, so that it return a Pivoted table when fields contain lat lon instead of using `s2_cell_id` to calculate GeoHash Coordinates.

fix: use lat lon fields and values instead of s2_cell_id

---

giraffe/package.json
giraffe/src/components/AnnotationLayer.tsx
giraffe/src/components/AnnotationLine.tsx
giraffe/src/components/AnnotationTooltip.tsx
giraffe/src/components/SizedPlot.tsx
giraffe/src/types/index.ts
package.json

Adds an onClick handler to the `annotationLine` polygon [triangle] pin. This would enable the retrieval of the ID of the annotation clicked, in UI and perform edit/delete operations on the respective annotations. 
This PR will also adjust where the tooltip is rendered so that it isn't in the way of the triangle target.
Will have to bump up Giraffe version for publishing. 
Screenshot for reference:

feat: annotations pin target onClick handler

---

giraffe/src/components/Geo.tsx

closes #519 
Alright so with this link updated this issue is closed. Also i checked with the truncated limits and although mapbox does not have any specific defined limits in the docs. And i did test the marker map since thats currently active map and it seems like beyond 2000 led to lag. I am writing and linking a separate issue to determine if we cause the lag or if its mapbox

fix: update the doc link

---

giraffe/src/components/AnnotationTooltip.tsx
giraffe/src/constants/index.ts
stories/src/helpers.tsx

closes: #525
addresses: https://github.com/influxdata/ui/issues/1121
we realized that we need a way to handle the tooltip caret position, [issues:  #525, https://github.com/influxdata/ui/issues/1121]. This PR attempts to provide a solution. Following is a brief about of how how we ended up with this solution. 
First we thought that the issue in https://github.com/influxdata/ui/issues/1121 would be solved by limiting the width of the tooltip box. But we quickly realized that there are some edge cases (literally) which we don't think would be covered by just limiting the size of the tooltip.
For example, this annotation in the corner renders its caret, in between the two lines, because at it's current state its programmed to render the caret in the middle of the tooltip box.
To address …

fix: use better positioning for the AnnotationTooltip caret and add maxWitdh to tooltip

---

giraffe/package.json
giraffe/src/utils/annotationData.ts

closes: #531
https://github.com/influxdata/ui/issues/1117
Tooltips are covering each other when annotations are close to each other. We want to only show a single annotation tooltip at once.
We filter out the annotation to show the tooltip, by calculating what annotation is closest by distance to the mouse pointer.
TODO: bump up giraffe version for publishing
Video:
https://user-images.githubusercontent.com/18511823/114090196-f6889180-986b-11eb-805c-54b67d2095c6.mov

fix: filter out the closest annotation to the mouse to show tootip on

---

giraffe/package.json
giraffe/src/components/Plot.tsx

Fixes failing e2e tests in ui's pipeline where the version is 2.7.2 or 2.7.3
`<Plot>` children were not being passed down and therefore the existing code in ui ignored everything between `<Plot></Plot>` such as the old way of doing Graph + Single Stat

fix: pass <Plot> children down

---

giraffe/package.json
giraffe/src/constants/index.ts
giraffe/src/utils/legend/useTooltipStyle.ts

Closes: https://github.com/influxdata/giraffe/issues/535
We had an edge case that we missed when calculating the tooltip position. Previous behavior would calculate the positioning when the annotation is on the edge. This PR fixes it so the calculation is correct and the tooltip position is right. 
Co-authored by: Bucky Schwarz (@hoorayimhelping) 
Screenshot:
Big sized tooltip:
Medium-sized tooltip:
Small sized tooltip:
Annotation away from the edge works fine too:

fix: fix tooltip positioning when on the edge of the screen

---

giraffe/package.json
giraffe/src/components/AnnotationLine.tsx

This PR addresses some annotation UX/Visuals stuff: 
The issues were:
* The caret (click target) on the top was a bit too big and ended up covering too much of the graph.
* The annotation lines being solid feel intrusive and that there wasn't enough of a separation between annotations and the actual graph.
We address this by making the caret small and the annotation line a dashed line.
Screenshot:

feat: small caret size and dashed annnotation line

---

giraffe/package.json
giraffe/src/components/AnnotationTooltip.tsx

closes: #543
This fixes an issue where the text is a single very long string without breaks was overflowing out of the div.
fix: add css property:  `overflowWrap: 'break-word'`
Note for the reviewer: I tried making a variable to apply the common style to both the title and description `div` elements but kept getting typescript errors. The following was not working.
```
const textContainerStyle = {
overflowWrap: 'break-word',
}
...
<div style={textContainerStyle}>{data.title}</div>
```
Before vs After:

fix: apply 'break-word' to prevent overflow of annotation tooltip text

---

stories/.storybook/config.js

Looks like Storybook changed their styling of the page to insert padding when "fullscreen" is not selected. This causes scrollbars to appear.
Let's remove them.
BEFORE:
AFTER:

chore: use fullscreen layout in storybook to remove unncessary scrollbars

---

giraffe/package.json
giraffe/src/components/SizedPlot.test.tsx
giraffe/src/components/SizedPlot.tsx
giraffe/src/types/index.ts
giraffe/src/utils/nearestTimestamp.ts
giraffe/src/utils/neartestTimestamp.test.ts

closes influxdata/ui#1265
Timestamps in the graph domain have their dates rounded off based on the size of the domain (so instead of 12:25:33:333 -> 12:25:30). Previously, using the raw `valueX` value from the hover interaction would get the raw timestamp at the point where the mouse is hovering. We now find the nearest rounded timestamp in the domain and set the annotation's time to that.

feat: clamp hoverX interaction handler to nearest rounded timestamp

---

giraffe/src/components/SizedPlot.tsx

The recent re-organization of the `Plot` and `SizedPlot` with new components added in between has brought to light that we must be very careful with changes, as this is the entry point into the heart of the code.
`env.getSpec` can actually return `null` even though it may not happen everywhere. It's still better to guard against this.

fix: add optional chaining to protect against null from getSpec

---

giraffe/package.json
giraffe/src/components/StaticLegendBox.tsx
giraffe/src/transforms/line.ts
giraffe/src/types/index.ts
giraffe/src/utils/fixtures/randomTable.ts
giraffe/src/utils/legend/sort.test.ts
giraffe/src/utils/legend/sort.ts
giraffe/src/utils/legend/staticLegend.test.ts
giraffe/src/utils/legend/staticLegend.ts
giraffe/src/utils/legend/tooltip.test.ts
giraffe/src/utils/legend/tooltip.ts
giraffe/src/utils/randomTable.ts
stories/src/linegraph.stories.tsx
stories/src/staticLegend.stories.tsx

Closes #548 
Adds additional columns in the Static Legend when the line graph is a stacked line layer:

feat: add additional columns to Static Legend for stacked line layer

---

giraffe/README.md
giraffe/src/components/StaticLegendBox.tsx
giraffe/src/types/index.ts

In support of https://github.com/influxdata/ui/issues/806
- A consuming app may need to adjust `margin` and `padding` around the Static Legend Box, allow this.
- Other styles can be added without further interface changes.
- Does not affect commonly-used strategically-important styles previously defined in the interface.

feat: update Static Legend interface

---

giraffe/src/utils/lineData.ts

fix: force coercion of falsy values to 0
guards against https://github.com/d3/d3-scale/releases/tag/v3.2.4
Issue: on april 28th 2021, we found an issue when we upgraded multiple giraffe libraries. This resulted in our graphs intermittently coming back empty/blank. This was because we had originally believed the null values would return 0, as d3-scale did originally. But by upgrading this broke and we were receiving NaN values. These values made it so our graphs could not be displayed properly but only broke on graphs with undefined values.

fix: this is what broke everything

---

stories/src/annotation.stories.tsx
stories/src/helpers.tsx

Closes #532 
Adds a `style` prop to `PlotContainer` to allow for specifying CSS Properties such as margin for the `PlotContainer`

feat: add style prop to PlotContainer

---

giraffe/package.json
giraffe/src/components/Legend.tsx
giraffe/src/components/LegendStyles.ts
giraffe/src/components/StaticLegendBox.tsx

Closes #574 
- Adds `DapperScrollbars` to the Static Legend when its content is too big to fit in the available space
- Does **_not_** allow a config-specified scrollbars element (this is too much scope)

feat: add scrollbars to the static legend

---

giraffe/package.json
giraffe/src/utils/PlotEnv.ts

Not all layers will create a spec, such as `RawFluxDataTable`, `Gauge`, `Geo`, `Custom`, `SingleStat`, and `Table`.
See https://github.com/influxdata/giraffe/blob/master/giraffe/src/utils/PlotEnv.ts#L375-L381
As such, guard against accessing a property on null.

fix: add null check in PlotEnv

---

giraffe/package.json
giraffe/src/components/AnnotationLayer.tsx
giraffe/src/components/AnnotationLine.tsx
giraffe/src/components/AnnotationTooltip.tsx
giraffe/src/components/Brush.tsx
giraffe/src/components/SizedPlot.test.tsx
giraffe/src/components/SizedPlot.tsx
giraffe/src/types/index.ts
giraffe/src/utils/annotationData.ts
giraffe/src/utils/useDragEvent.ts
stories/src/annotation.stories.tsx

for giraffe#585
this PR is all about drawing annotations.
users of this library (ui, in our case) has its own listeners for graph interaction to add annotations
added a new interaction handler; so that when brushing on the x axis, a callback other than zoom can be invoked
also: differentiating now properly between drags and single clicks.

feat: drawing range annotations

---

giraffe/src/components/SizedPlot.tsx

1) refactors the allowed annotation spec types to a set that can be easily expanded
2) requires that defaultType includes property `lineData` before enabling annotations
3) ensures that defaultType exists

chore: refactor spec types to set

---

giraffe/package.json
giraffe/src/index.ts

Exports `createGroupIDColumn` to allow consuming apps to create the proper order for the `fill` property

feat: export createGroupIDColumn

---

giraffe/package.json
giraffe/src/components/BandLayer.tsx
giraffe/src/components/LineLayer.tsx
giraffe/src/components/SizedPlot.tsx
giraffe/src/types/index.ts
stories/package.json

Part of https://github.com/influxdata/ui/issues/1456
To avoid confusing the user and leading them to thinking there's a bug, the hover layer should be disabled when `legendHide` is truthy.
When disabled, the cursor is now 'auto' (not a crosshair), and there is no guide wire. 
https://user-images.githubusercontent.com/10736577/120868518-13c69d00-c549-11eb-82a0-05dca0750fd4.mp4

feat: disable the hover layers for line and band when legendHide is truthy to avoid confusing the user

---

giraffe/package.json
giraffe/src/components/Brush.tsx
giraffe/src/components/SizedPlot.test.tsx
giraffe/src/components/SizedPlot.tsx
giraffe/src/types/index.ts
giraffe/src/utils/useDragEvent.ts

now the user must hold the shift key down when clicking to create a point annotation.
updated the interaction listener code (added a new one, kept the old one in for backwards compatibility for other users)
also bumped up the version number

chore: change to shift click

---

giraffe/package.json
giraffe/src/components/StaticLegendBox.tsx
stories/package.json

In support of https://github.com/influxdata/ui/issues/1749
By removing the absolute position in static legend, consuming apps have a much easier time styling the static legend and its parent elements to handle overflow, such as with scrollbars. Everything still looks the same with these changes.

fix: remove absolute positioning in static legend for easier styling

---

giraffe/package.json
giraffe/src/utils/useDragEvent.ts
stories/package.json

Closes #628
I think this is a longstanding memory leak. It looks like it was mistakenly added in this [two year old PR.](https://github.com/influxdata/giraffe/commit/80822c79190a07aae3495077842a6a1b15e291c8#diff-795c398b1510d545f8ae5cdee91c58b3b66886f987c1fea1bb2855d50bf190e4R82) Looks like a bad copy/paste job to me.
To reproduce the bug in UI:
1. Create a graph in a cell in a dashboard
1. Do something in the graph that causes one of the callback functions in SizedPlot to fire. e.g.: Drag to resize, add an annotation, etc.
1. Navigate away from the graph. I usually go to Explore
1. Click Boards. The error should fire.
To test the fix:
1. `yarn start`
2. `npm pack`
3. from ui: `yarn cache clean && yarn add $path_to_packed_file` (it's important to clear your cache)
4. repeat the steps …

fix: changed unused event removal for mousemove; use mouseup

---

giraffe/package.json
giraffe/src/components/AnnotationTooltip.tsx
giraffe/src/components/Tooltip.tsx
giraffe/src/utils/legend/useTooltipElement.ts
stories/package.json

Part of #630 
- refactors a conditional usage of hooks into separate hooks with no change in behavior
- Addresses 2 errors:
```
/giraffe/src/utils/legend/useTooltipElement.ts
33:5  error  React Hook "useAnnotationStyle" is called conditionally. React Hooks must be called in the exact same order in every component render  react-hooks/rules-of-hooks
35:5  error  React Hook "useTooltipStyle" is called conditionally. React Hooks must be called in the exact same order in every component render     react-hooks/rules-of-hooks
```

refactor: remove conditional hooks usage for useTooltipElement

---

giraffe/package.json
giraffe/src/components/geo/processing/NativeGeoTable.ts
stories/package.json
stories/src/geo.stories.tsx
stories/src/helpers.tsx

Turns out there was a hardcoded value being used for using `s2_cell_id` to get lat/lon coordinates. I updated NativeGeoTable to use the selected s2Column

fix: update native geo table to use s2 column

---

giraffe/package.json
giraffe/src/components/AnnotationTooltip.tsx

to support ui#1124
https://app.zenhub.com/workspaces/applicationdumplings-60a80d872533670017a6b107/issues/influxdata/ui/1124
divides up the annotation text using the newline ('/n') string.

fix: enable multi line annotation tooltips

---

giraffe/package.json
giraffe/src/components/AnnotationLayer.tsx
giraffe/src/components/AnnotationLine.tsx
giraffe/src/components/SizedPlot.tsx
stories/src/annotation.stories.tsx

easier clicking now that the hover legend is hidden when the mouse is on a clickable annotation top (either the range 'hat' or the point 'diamond')
if the legend is already hidden then this is a no-op.  nothing happens.  (because there is nothing to hide)
for ui#1119

fix: annotations much easier to click on

---

giraffe/src/components/SimpleTable/PaginationNav/Pagination.scss
giraffe/src/components/SimpleTable/SimpleTableGraph.scss
giraffe/src/components/SimpleTable/Table/Table.scss

Closes: #646
3 groups of styles were removed:
- Unused colors and component sizes
- Variables that were only used once. Uses of the variables were directly replaced with the value.
- Mixins because they were either unused or their use was an extra step.

chore: Remove unnecessary styles in Pagination.scss, SimpleTableGraph.scss, and Table.scss 

---

giraffe/src/components/MultiGrid.tsx

Part of #630 
Resolves the lint error for
```/giraffe/src/components/MultiGrid.tsx
601:28 error React Hook "useForceUpdate" is called in function "forceUpdate" that is neither a React function component nor a custom React Hook function. React component names must start with an uppercase letter react-hooks/rules-of-hooks```

fix: remove unnecessary wrapped function to resolve lint error

---

giraffe/src/components/Plot.tsx

Part of #630 
Resolves the lint error for
```
/giraffe/src/components/Plot.tsx
16:19 error React Hook "useRef" is called conditionally. React Hooks must be called in the exact same order in every component render react-hooks/rules-of-hooks
17:20 error React Hook "useRef" is called conditionally. React Hooks must be called in the exact same order in every component render react-hooks/rules-of-hooks
```

fix: remove conditional usage of useRef hook

---

giraffe/src/components/geo/CircleMarkerLayer.tsx
giraffe/src/components/geo/GeoTooltip.tsx
giraffe/src/components/geo/PointMapLayer.tsx

Part of #630 
Resolves lint errors for
``` 
/giraffe/src/components/geo/CircleMarkerLayer.tsx
83:9 warning React Hook useLayoutEffect received a function whose dependencies are unknown. Pass an inline function instead react-hooks/exhaustive-deps
83:9 error React Hook "useLayoutEffect" cannot be called inside a callback. React Hooks must be called in a React function component or a custom React Hook function react-hooks/rules-of-hooks
/giraffe/src/components/geo/PointMapLayer.tsx
71:9 warning React Hook useLayoutEffect received a function whose dependencies are unknown. Pass an inline function instead react-hooks/exhaustive-deps
71:9 error React Hook "useLayoutEffect" cannot be called inside a callback. React Hooks must be called in a React function component or a custom React Hook …
```

fix: move useLayoutEffect into component to resolve lint error

---

giraffe/src/components/Geo.tsx

Part of #630 
Resolves the lint error for
```
/giraffe/src/components/Geo.tsx
46:3 error React Hook "useEffect" is called conditionally. React Hooks must be called in the exact same order in every component render. Did you accidentally call a React Hook after an early return? react-hooks/rules-of-hooks
51:53 error React Hook "useState" is called conditionally. React Hooks must be called in the exact same order in every component render. Did you accidentally call a React Hook after an early return? react-hooks/rules-of-hooks
63:3 error React Hook "useEffect" is called conditionally. React Hooks must be called in the exact same order in every component render. Did you accidentally call a React Hook after an early return? react-hooks/rules-of-hooks
```

fix: move early return after all hooks

---

.eslintrc.json
giraffe/package.json
stories/package.json
yarn.lock

Closes #630 
All React hooks lint errors have been addressed. Let's put the linter in place to let developers know when a hook is not used with best practices in mind.

feat: activate linting for React hooks

---

giraffe/package.json
giraffe/src/components/TableCell.tsx
stories/src/data/tableGraph.ts

Closes: https://github.com/influxdata/idpe/issues/10645
Our table was formatting `string` dataType that were numbers, as numbers. This is because we use `isNaN` to make the decision, I added a layer around those checks to check whether the dataType of the flux column is `string` in the first place. 
Screen shots: 
`_value` column dataType `string`
`_value` column dataType `double`

fix: strings that are numbers still render as strings

---

giraffe/package.json

Not sure what happened [here](https://github.com/influxdata/giraffe/pull/673/files#diff-d7304a1c6249c5809204275173f61db450795e4a8f4be6a532b3c84d4a71a182R3), it showed a diff so I thought the bump was successful but we already have `v2.18.2`. 
This bumps the version to `2.18.3`

chore: v2.18.3

---

giraffe/package.json
giraffe/src/constants/index.ts

Closes: #674
We need to change the color of the crosshair line so that the line is more visible.

feat: adjust cross hair visibility by changing it's color

---

giraffe/package.json
giraffe/src/components/SimpleTable/Table/TableHeaderCell.tsx

Part of https://github.com/influxdata/ui/issues/2035
Just a simple css change to align the table headers better. We cant yet close the UI#2035 issue yet because there are two version of simple table, one giraffe's (behind the `useGiraffeGraphs` flag) and he other is in UI.

fix: valign the table header cell

---

giraffe/package.json
giraffe/webpack.common.config.js
stories/package.json

Clean up. Sanity check looks good. Maps are loading in storybook with styles.

chore: remove duplicate rule for css in webpack config

---

giraffe/package.json
stories/package.json

Hi there!
This change adds the repository property to your package.json file(s). Having this available provides a number of benefits to security tooling. For example, it allows for greater trust by checking for signed commits, contributors to a release and validating history with the project. It also allows for comparison between the source code and the published artifact in order to detect attacks on authors during the publication process.
We validate that we're making a PR against the correct repository by comparing the metadata for the published artifact on [npmjs.com](www.npmjs.com) against the metadata in the package.json file in the repository.
This change is provided by a team at Microsoft -- we're happy to answer any questions you may have. (Members of this team include …

feat: update package.json to include the repository

---

giraffe/package.json
stories/package.json
yarn.lock

Build error was happening for canvas - "command failed" here: https://app.circleci.com/pipelines/github/influxdata/giraffe/1848/workflows/61b7d0d5-8999-4945-af8a-4663db1e278a/jobs/1738
Build error was happening for node-sass - "command failed" here: https://app.circleci.com/pipelines/github/influxdata/giraffe/1849/workflows/13b13ff0-9001-4f65-9b1a-23509be40f05/jobs/1739
Updating these two dependencies seems to resolve these errors.
Note: with these upgrades, there is warning from Storybook regarding `caniuse-lite` seen here. Running the suggested command does NOT make the warning go away.

fix: update canvas and node sass

---

giraffe/src/utils/legend/useTooltipElement.ts
stories/.storybook/addons.js
stories/.storybook/config.js
stories/.storybook/main.js
stories/.storybook/manager.js
stories/package.json
stories/src/annotation.stories.tsx
stories/src/band.stories.tsx
stories/src/helpers.tsx
stories/src/index.stories.tsx
stories/src/linegraph.stories.tsx
stories/src/scatterplot.stories.tsx
stories/src/staticLegend.stories.tsx
stories/src/utilities.stories.tsx
yarn.lock

- upgrade storybook from 5.0.11 to 5.3.21
- fix (fairly unhelpful) TypeScript errors
- refactor some stories based on TypeScript failures
- tweak `cpuKnob` helper function to return the CPU Table (the knob didn't work anyway)
-

chore: upgrade storybook to 5.3.21

---

stories/.storybook/preview.js

We do need this file but it should be named `preview.js`. It prevents the unsightly vertical scrollbar in storybook

chore: bring back config.js as preview.js to prevent vertical scrollbar

---

stories/src/linegraph.stories.tsx

There is a console error in the browser if we use `NaN` but the knob requires 2 arguments of the number type.
We can work around all of this by using a text knob and then interpreting the input from the text knob into the proper config property to be passed into the `<Plot>`

chore: update the story by using a string knob to handle undefined input

---

stories/src/staticLegend.stories.tsx

A continuation of https://github.com/influxdata/giraffe/pull/708
Do this same trick for Static Legend stories

chore: use string knob to handle undefined user input in Static Legend stories

---

giraffe/package.json
stories/package.json
yarn.lock

Closes #564 
This is meant to be done in concert with [clockface](https://github.com/influxdata/clockface/pull/705)
When both of these PRs are merged in and released, we'll update the UI so that giraffe, clockface and ui all have the same version of React
very low risk feature set: https://github.com/facebook/react/blob/main/CHANGELOG.md#16140-october-14-2020
I've tested this locally in storybook and in ui. I couldn't find any regressions in the UI consumption of this change.

chore: upgrade from react 16.8.0 to react 17.0.2

---

giraffe/package.json
giraffe/src/components/DapperScrollbars.scss
giraffe/src/components/Input.scss
giraffe/src/components/TableGraphs.scss
stories/package.json

Migrate away from using slash for division in Sass

chore: migrate sass division

---

giraffe/src/utils/useMousePos.ts

When a page contained more graphs than the page could fit, the tooltip would disappear if scrolling down/to the right. This fix makes the Tooltip show for all graphs on these type of pages.
Closes #680

fix: Broken Tooltip

---

giraffe/package.json
giraffe/src/components/LegendStyles.ts
stories/package.json

Closes #719 
Allows long column names.
In cases where the columns are so many and the names are so long, which may obscure some of the later columns, the user has access to mitigations including orientation and a static legend with scrolling.

feat: allow long column names in legends and tooltips

---

giraffe/README.md
giraffe/package.json
giraffe/src/utils/fromFlux.test.ts
giraffe/src/utils/fromFlux.ts
stories/package.json

Closes #726 
Adds a property to hold all of the result column names in the annotated CSV from the results of a Flux query. This allows the `fromFlux` utility to assist the developer in identifying valid result column names, which in turn can simplify user interface validation of visualization configuration options and properties.

feat: enhance fromFlux utility to include all result column names

---

giraffe/package.json
giraffe/src/utils/fromFlux.test.ts
giraffe/src/utils/fromFlux.ts
stories/package.json

Part of #726 
According to the [Flux spec](https://github.com/influxdata/flux/blob/master/docs/SPEC.md#csv) the result column is not necessarily guaranteed to be the first column when present.
Update `fromFlux` to guard against an unexpected change to Flux query results that would still be considered within its spec.

fix: update fromFlux to allow result column to be in any position

---

giraffe/package.json
giraffe/src/components/BandHoverLayer.tsx
giraffe/src/components/BandLayer.tsx
giraffe/src/components/PlotResizer.tsx
giraffe/src/transforms/band.ts
giraffe/src/utils/normalizeConfig.test.ts
giraffe/src/utils/normalizeConfig.ts
stories/package.json

Part of https://github.com/influxdata/ui/issues/3404
- Creates a normalizer to set the `config` including the `layers` to acceptable defaults and expectations. This is also the starting point for a separate bigger issue (see https://github.com/influxdata/giraffe/issues/447)
BEFORE, without normalization:
https://user-images.githubusercontent.com/10736577/153316844-83c3fd57-a520-4248-b77b-1eb6a42ca0de.mp4
AFTER, with normalization:
https://user-images.githubusercontent.com/10736577/153316876-29b6e61d-7cd0-4b2d-89d8-dc24a5ddc02d.mp4

fix: ensure Band's mainColumnName cannot be reused for lower and upper

---

giraffe/package.json
giraffe/src/utils/normalizeConfig.test.ts
giraffe/src/utils/normalizeConfig.ts
stories/package.json

Part of https://github.com/influxdata/ui/issues/3404  
Sorry, i typed too quickly and the autocomplete picked the wrong variable which i mistakenly accepted. This corrects the typo and adds additional unit tests.

fix: fix typo to check against mainColumnName correctly

---

giraffe/package.json
stories/package.json

Bumping version numbers to do a publish.
We will be testing if `npm publish` is any different than `yarn publish` and if the publishing has any issue completing.

chore: update version numbers

---

.gitignore

**npm** requires new steps to publish when requiring 2FA (two-factor authentication). One of the steps involves inserting a token into your local **.npmrc** file, which should remain local so that we do not leak tokens.
- add **.npmrc** to **.gitignore**

chore: add .npmrc to gitignore to support publishing without leaking tokens

---

giraffe/package.json
giraffe/publish
stories/package.json

Allows the `publish` script to proceed even with a dirty working tree.

chore: update version number for demo

---

.github/workflows/semantic.yml

The github application "semantic-pull-requests" uses a very old node version and presents security vulnerabilities. The repo manager has not addressed the issue and has become nonresponsive. Influxdata has its own solution based in github reusable workflows.  
**This change is org-wide to address security vulnerabilites in semantic-pull-requests, by removing it.**
Remove semantic-pull-requests.  Add https://github.com/influxdata/validate-semantic-github-messages

refactor: Deprecate and remove semantic-pull-requests, insert influxdata replacement reusable workflow solution.

---

giraffe/package.json
giraffe/src/index.ts
giraffe/src/utils/fromFlux.test.ts
giraffe/src/utils/fromFlux.ts

Closes #750 
This PR brings a significant improvement to the `fromFlux` parser by doing two things:
1. updating the `splitChunks` function to use a more linear, less memory-intensive approach
2. removing the `parseValue` function for inline conditionals to reduce memory-usage of a function that's generated every time a deeply nested loop runs.
Before:
After:
While this solution does replace a like-for-like version of the fromFlux parser functionality, it should by no means be considered a final solution to the problem. The current implementation can and should be iterated upon. More specifically, the parsing process is about chunking the data, parsing it, restructuring it, and rejoining it. We should simplify this by using pointer references and getting the relevant data that way, rather …

feat: improve fromFlux performance

---

giraffe/package.json
giraffe/src/utils/fromFlux.ts
stories/package.json

This PR consolidates the changes that were made here:
https://github.com/influxdata/giraffe/pull/752
The linked PR was made to help address some performance issues with the fromFlux parser. After merging the changes in, publishing a new version of giraffe in the UI, and feature flagging the usages of fromFlux in the UI to use the `fastFromFlux` the parser changes appear to have improved the UI's usage of the parser without any known issues. Having said that, this implementation still relies upon allocating memory for chunks of data that are then parsed, chunked and joined again. While this imperfect implementation is a lot better than the previous one, we want to be able to iterate on the `fastFromFlux` parser without compromising gains made to the parser.
This PR basically just updates …

chore: clean up drift between parsers after proven success

---

giraffe/package.json
giraffe/src/utils/fromFlux.test.ts
giraffe/src/utils/fromFlux.ts
stories/package.json

This PR introduces a new way of parsing incoming CSV data by relying upon PapaParse as our central mechanism for parsing the CSVs. While the performance gains here are negligible, this should allow us to handle JSON values within the CSV. 
While the previous implementation of the parser relied upon the d3 based parser, this implementation transitions to using Papaparse. The reasons for this are:
1. More broad CSV support
2. Better handling of edge cases in parser logic when parsing tables that have JSON data
3. Easier implementation that can be transitioned to data streaming
4. Slight performance gains

feat: use papaparse as our parser

---

giraffe/package.json
giraffe/src/constants/colorSchemes.ts
stories/package.json
stories/src/helpers.tsx

Part of https://github.com/influxdata/ui/issues/4549
Adds a color blind friendly color scheme

feat: add color blind friendly color scheme

---

giraffe/package.json
giraffe/src/constants/colorSchemes.ts
stories/package.json
stories/src/helpers.tsx

Part of https://github.com/influxdata/ui/issues/5069
To avoid clashing with the background color, the color blind friendly pallet should be two pallets to allow the user to adjust to the background.
Light pallet:
Dark pallet:

fix: add a second color blind friendly pallet to avoid clashing with background color

---

giraffe/package.json
giraffe/src/utils/formatters.test.ts
giraffe/src/utils/formatters.ts
stories/package.json

Closes [#4429](https://github.com/influxdata/ui/issues/4429)
PR addresses bug ticket by condescending extremely large numbers (>10^30) by converting its SI value to scientific notation. 
Before fix: 
when data point = 1.7e308 is graphed with its Y-value unit prefix set to `SI`, we see 1 followed by ~50 zeros in the y axis. 
After fix: 
same data point graphs with 1.7e284Y value on the Y axis.

feat(Formatters): shorten numbers greater than septillion

---

giraffe/src/utils/fromRows.ts

While dealing with timestamps in milliseconds, inferColumnType() detects timestamp column type as a number. My first approach to fix that was to set a partial schema to only fix the column that was wrongly detected. But I found out that wasn't possible. This fixes that use case.

fix: accept partial schemas in fromRows

---

giraffe/package.json
giraffe/src/components/TableGraphs.scss
stories/package.json

Closes https://github.com/influxdata/ui/issues/5276  
The new icon set from Clockface added new icons and changed the ordering of the icon hex values. The correct value for "caret down" should be used in Table styling.
FIXED, ascending:
FIXED, descending:

fix: update caret down in Table styling to correct value

---

giraffe/package.json
giraffe/src/components/SimpleTable/SimpleTableGraph.scss
stories/package.json

Part of https://github.com/influxdata/ui/issues/3650
Missed one. Add this fix to SimpleTable.

fix: allow Safari users to select text

---

giraffe/package.json
giraffe/src/components/SimpleTable/PagedTable.tsx
stories/package.json

Part of https://github.com/influxdata/ui/issues/5317  
Matches the changes found here: https://github.com/influxdata/ui/pull/5318

fix: cap the estimated screen height

---

giraffe/package.json
giraffe/src/components/TableCell.tsx
stories/package.json

Closes #789 
Pr updates first row of table cell to be of button element instead of div. This prevents unintentional highlighting of 
header rows when clicked. 
Before:  
https://user-images.githubusercontent.com/66275100/185636775-54aca6a6-bb14-4771-9042-29e2d1613bbe.mp4
After:  
https://user-images.githubusercontent.com/66275100/185636661-741f680f-e5e2-4d19-a72c-e9a24941e130.mov

fix(TabelCell): update first row to be button

---

giraffe/package.json
giraffe/src/components/Band/BandLayer.tsx
giraffe/src/utils/lineData.test.ts
giraffe/src/utils/lineData.ts
stories/package.json

Closes #799 
In Band, avoid the Douglas Peucker algorithm, which sometimes returns fewer points of line data than it receives. Band must always have the same number of points for all lines.
BEFORE:
AFTER:

fix: update Band to avoid using the Douglas Peucker algorithm

---

giraffe/package.json
giraffe/src/components/SimpleTable/PagedTable.tsx
stories/package.json
stories/src/simpleTable.stories.tsx

Closes https://github.com/influxdata/ui/issues/5692
By changing the initial row height from 0 to a positive number, we dramatically speed up the height estimation used by Simple Table during rendering of large data sets. The actual row height will auto-correct after the initial guess.
https://user-images.githubusercontent.com/10736577/189460829-093e593e-0ca1-4b7f-94bd-c05a0233c419.mp4

fix: speeds up height calculations for Simple Table

---

package.json
yarn.lock

react-dev-utils 11.0.3 specifies shell-quote 1.7.2 precisely which is preventing dependabot automated security PRs for it. react-dev-utils didn't change this to ^1.7.3 until 12.0.1. Use a resolution to resolve to 1.7.3.

chore: use resolutions to use shell-quote 1.7.3

---

giraffe/package.json
giraffe/webpack.common.config.js
stories/package.json
yarn.lock

Helps with: https://github.com/influxdata/ui/issues/1673
Helps with:  https://github.com/influxdata/ui/issues/2629
In cloud environments, there are font loading errors that are thrown in the console on every page. These don't show up in development environments, and so this has been a historically difficult issue to reproduce.
I was finally able to do it by creating a minimal application that used Clockface and Giraffe. I was able to fix it by changing the webpack configuration of Giraffe to use `url-loader` instead of `font-loader` when loading webfonts. [This issue in webpack's repo](https://github.com/webpack/webpack/issues/7353) was extremely helpful.
Testing in the UI. If you clicked on one of the loaded fonts in the browser network tab, there would be an error when loading it. …

fix: change font loader from file-loader to url-loader

---

giraffe/package.json
giraffe/src/components/Plot.tsx
giraffe/src/components/PlotResizer.tsx
giraffe/src/components/SimpleTable/PagedTable.tsx
giraffe/src/components/SizedTable.tsx
giraffe/src/utils/hasPlotEnv.ts
stories/package.json

Part of #805  
Certain visualizations do not need the usePlotEnv hook, and the PlotEnv component which is very expensive. PlotEnv was also incorrectly being used twice (!) for `SizedTable`. Remove all usages completely.
Here is a video showing all of the non-PlotEnv visualizations working with the new split
https://user-images.githubusercontent.com/10736577/192071610-93362d29-a864-4bc4-976d-3554ae778c6b.mp4

fix: split out visualizations that do not use PlotEnv

---

giraffe/package.json
giraffe/src/utils/isDefined.test.ts
giraffe/src/utils/isDefined.ts
stories/package.json

While refactoring the Simple Table code for readability, I came across an issue with `isDefined`. Currently, `isDefined` uses `isNaN` as one of its underlying comparisons. However, the built-in `isNaN` is not the appropriate checker for `NaN` which is what our `isDefined` is trying to look for. The appropriate checker is `Number.isNaN`.
The differences can be seen in the console:
What we want: strings should be treated as separate from `NaN` and consequently `isDefined('string')` should return `true`.
Unit tests have been added to enforce this expectation, as well as other expectations.
**_EDIT_**: additionally, we will add a new function called `isDefinedOrNaN` to make clear that we are semantically calling `NaN` undefined. Having them in the same file makes clear how we treat `NaN` in …

fix: clarify the definition of isDefined

---

giraffe/package.json
giraffe/src/components/SingleStat/SingleStatLayer.tsx
giraffe/src/index.ts
giraffe/src/style/singleStatStyles.ts
giraffe/src/types/index.ts
stories/package.json
stories/src/singleStat.stories.tsx

Related to https://github.com/influxdata/ui/issues/5928
Adds an optional svg style to disable user select on the svg text for Single Stat. This allows click-drag behavior to work without selecting the svg text.
Chrome:
https://user-images.githubusercontent.com/10736577/193149655-d1b7e1da-1a04-492e-92a7-48b04674104c.mp4
Firefox:
https://user-images.githubusercontent.com/10736577/193149696-22ed20af-d80d-4db2-a7ea-3130044c3c81.mp4
Safari:
https://user-images.githubusercontent.com/10736577/193149736-c951071f-e192-4480-9b65-fbd2c880a3df.mp4
Edge:
https://user-images.githubusercontent.com/10736577/193149767-2a46ad41-16af-489f-b853-4e1ca37f25a1.mp4

feat: add optional svg style to disable user select for Single Stat

---

giraffe/package.json
giraffe/src/components/SimpleTable/PagedTable.tsx
stories/package.json

Closes #823 
BEFORE: data is hidden if available height is too small. MISLEADING!
https://user-images.githubusercontent.com/10736577/198398167-c7322066-679f-4730-94ca-631c593c9e99.mp4
AFTER: "hey user, there is something there! check it out"
https://user-images.githubusercontent.com/10736577/198398256-bc9cee48-583e-49fd-9c83-dd70c828a0ad.mp4

fix: allow Simple Table to render 1 row as minimum regardless of available height

---

package.json
yarn.lock

* chore: resolve loader-utils 2.0.x to ^2.0.3
* chore: resolve loader-utils 1.x to ^1.4.1
These resolutions should be able to be removed once giraffe moves to webpack5, which allows other devDependencies to be upgraded. For now, resolve loader-utils to 2.0.3 and 1.4.1 to address dependabot.

chore: add resolutions for loader-utils
